### ISSUE TITLE
VS2017 tries to include glm.lib after adding fips-glm

### ISSUE THREAD

**Issue by mattiasljungstrom** [floooh/fips-glm#1]
fips.yml file:

policies:
  no_auto_import: true
imports:
  sokol:
    git: https://github.com/floooh/sokol
  fips-glfw:
    git: https://github.com/fips-libs/fips-glfw
  fips-imgui:
    git: https://github.com/fips-libs/fips-imgui.git
  fips-glm:
    git: https://github.com/fips-libs/fips-glm.git

Building gives:
LINK : fatal error LNK1104: cannot open file 'glm.lib'

The project shouldn't add glm.lib, since glm is a header only library. How can I change the configuration to fix this? Thanks!

**Comment by floooh** [comment]
Yeah, that's weird... I just played around with the fips-hello-world sample a bit, set the no_auto_import policy and import fips-glm, and I get that behaviour when I add a ```fips_deps(glm)``` to the executable definition, in this case a linker dependency glm.lib would be added (even though no such cmake target exists).

Do you have such a ```fips_deps(glm)``` or ```fips_libs(glm)``` anywhere by any chance? This isn't required for such header-only libs

**Comment by mattiasljungstrom** [comment]
Right, I had it in my fips_deps() list. Thanks for helping out!
