### ISSUE TITLE
Upgrade to newer glm

### ISSUE THREAD

**Issue by msv68** [floooh/fips-glm#2]
Please upgrade the submodule glm to the newest stable version.  
I propose to use the tag 0.9.9.6.  
This will allow getting rid of numerous compiler warnings when building with modern compilers. I use gcc 7.4.0.

**Comment by msv68** [comment]
Dear Andre, 
You can add me as a collaborator in your project, and I will create a branch and pull request to merge into master.
Best regards,
Mikhail

**Comment by msv68** [comment]
@floooh FYI

**Comment by floooh** [comment]
I'll take care of that ASAP :)

**Comment by floooh** [comment]
Hmm... problem, the Oryol samples are broken after updating. I remember that there was some behaviour change in GLM regarding object initialization which requires code changes.

I'll need to delay the update until I get around to investigate and fix that.

I'd recommend that you fork your own version of fips-glm for now and use that.

**Comment by floooh** [comment]
Ah ok, I figured out the solution, GLM has a new config define GLM_FORCE_CTOR_INIT to get the old behaviour.

One important thing: the "proper" fips-glm repository is actually here: https://github.com/fips-libs/fips-glm.

**Comment by floooh** [comment]
Ok, https://github.com/fips-libs/fips-glm has been updated to 0.9.9.6

**Comment by msv68** [comment]
Thanks. 
Strange, I did not get any notifications about your posts here. Accidentally came here and found out that you have solved this issue.
I did the same define GLM_FORCE_CTOR_INIT in my code to get rid of regressions.
